In [83]:
import pandas as pd

In [84]:
df = pd.read_csv('WineQT.csv')

In [85]:
s=pd.Series([10,20,30])
s

0    10
1    20
2    30
dtype: int64

In [86]:
s+5
print(s)

0    10
1    20
2    30
dtype: int64

In [87]:
print(type(s))

<class 'pandas.core.series.Series'>

In [88]:
type(df)

pandas.core.frame.DataFrame

In [89]:
pd.Series([10,20,30], index = ["a","b","c"])

a    10
b    20
c    30
dtype: int64

In [90]:
pd.Series({"a":1,"b":2})

a    1
b    2
dtype: int64

In [91]:
s.values

array([10, 20, 30])

In [92]:
s.index

RangeIndex(start=0, stop=3, step=1)

In [93]:
s.size

3

In [94]:
s.dtype

dtype('int64')

In [95]:
#mean/average
s.mean()

np.float64(20.0)

In [96]:
#maximun
s.max()

np.int64(30)

In [97]:
#minimum
s.min()

np.int64(10)

In [98]:
#standard deviation
s.std()

np.float64(10.0)

In [99]:
#frequency count
s.value_counts()

10    1
20    1
30    1
Name: count, dtype: int64

In [100]:
a=pd.DataFrame([1,2],[3,4])
print(a)
type(a)

   0
3  1
4  2

pandas.core.frame.DataFrame

In [101]:
pd.DataFrame({'A':[1,2],'B':[3,4]})

   A  B
0  1  3
1  2  4

In [102]:
df.head(3)

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,0
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5,1
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5,2

In [103]:
df.head(-1142)

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id
0,7.4,0.7,0.0,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,0

In [104]:
df.tail(1)

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id
1142,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5,1597

In [105]:
#random 5 sample data
df.sample(5)

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id
797,10.0,0.430,0.33,2.7,0.095,28.0,89.0,0.99840,3.22,0.68,10.0,5,1128
877,6.5,0.670,0.00,4.3,0.057,11.0,20.0,0.99488,3.45,0.56,11.8,4,1239
776,8.4,0.340,0.42,2.1,0.072,23.0,36.0,0.99392,3.11,0.78,12.4,6,1100
519,6.4,0.865,0.03,3.2,0.071,27.0,58.0,0.99500,3.61,0.49,12.7,6,729
979,7.5,0.570,0.02,2.6,0.077,11.0,35.0,0.99557,3.36,0.62,10.8,6,1380

In [106]:
df.sample(3,ignore_index=True)

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id
0,6.6,0.58,0.02,2.4,0.069,19.0,40.0,0.99387,3.38,0.66,12.6,6,1335
1,7.5,0.57,0.02,2.6,0.077,11.0,35.0,0.99557,3.36,0.62,10.8,6,1379
2,7.2,0.33,0.33,1.7,0.061,3.0,13.0,0.99600,3.23,1.10,10.0,8,1403

In [107]:
df.ndim

2

In [108]:
df.shape

(1143, 13)

In [109]:
df.size

14859

In [110]:
df.columns

Index(['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
       'pH', 'sulphates', 'alcohol', 'quality', 'Id'],
      dtype='object')

In [111]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1143 entries, 0 to 1142
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   fixed acidity         1143 non-null   float64
 1   volatile acidity      1143 non-null   float64
 2   citric acid           1143 non-null   float64
 3   residual sugar        1143 non-null   float64
 4   chlorides             1143 non-null   float64
 5   free sulfur dioxide   1143 non-null   float64
 6   total sulfur dioxide  1143 non-null   float64
 7   density               1143 non-null   float64
 8   pH                    1143 non-null   float64
 9   sulphates             1143 non-null   float64
 10  alcohol               1143 non-null   float64
 11  quality               1143 non-null   int64
 12  Id                    1143 non-null   int64
dtypes: float64(11), int64(2)
memory usage: 116.2 KB

In [112]:
df.describe()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id
count,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000
mean,8.311111,0.531339,0.268364,2.532152,0.086933,15.615486,45.914698,0.996730,3.311015,0.657708,10.442111,5.657043,804.969379
std,1.747595,0.179633,0.196686,1.355917,0.047267,10.250486,32.782130,0.001925,0.156664,0.170399,1.082196,0.805824,463.997116
min,4.600000,0.120000,0.000000,0.900000,0.012000,1.000000,6.000000,0.990070,2.740000,0.330000,8.400000,3.000000,0.000000
25%,7.100000,0.392500,0.090000,1.900000,0.070000,7.000000,21.000000,0.995570,3.205000,0.550000,9.500000,5.000000,411.000000
50%,7.900000,0.520000,0.250000,2.200000,0.079000,13.000000,37.000000,0.996680,3.310000,0.620000,10.200000,6.000000,794.000000
75%,9.100000,0.640000,0.420000,2.600000,0.090000,21.000000,61.000000,0.997845,3.400000,0.730000,11.100000,6.000000,1209.500000
max,15.900000,1.580000,1.000000,15.500000,0.611000,68.000000,289.000000,1.003690,4.010000,2.000000,14.900000,8.000000,1597.000000

In [113]:
df.describe(include='float')

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol
count,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000
mean,8.311111,0.531339,0.268364,2.532152,0.086933,15.615486,45.914698,0.996730,3.311015,0.657708,10.442111
std,1.747595,0.179633,0.196686,1.355917,0.047267,10.250486,32.782130,0.001925,0.156664,0.170399,1.082196
min,4.600000,0.120000,0.000000,0.900000,0.012000,1.000000,6.000000,0.990070,2.740000,0.330000,8.400000
25%,7.100000,0.392500,0.090000,1.900000,0.070000,7.000000,21.000000,0.995570,3.205000,0.550000,9.500000
50%,7.900000,0.520000,0.250000,2.200000,0.079000,13.000000,37.000000,0.996680,3.310000,0.620000,10.200000
75%,9.100000,0.640000,0.420000,2.600000,0.090000,21.000000,61.000000,0.997845,3.400000,0.730000,11.100000
max,15.900000,1.580000,1.000000,15.500000,0.611000,68.000000,289.000000,1.003690,4.010000,2.000000,14.900000

In [114]:
df.describe(include='int')

           quality           Id
count  1143.000000  1143.000000
mean      5.657043   804.969379
std       0.805824   463.997116
min       3.000000     0.000000
25%       5.000000   411.000000
50%       6.000000   794.000000
75%       6.000000  1209.500000
max       8.000000  1597.000000

In [115]:
#shows datatypes
df.dtypes

fixed acidity           float64
volatile acidity        float64
citric acid             float64
residual sugar          float64
chlorides               float64
free sulfur dioxide     float64
total sulfur dioxide    float64
density                 float64
pH                      float64
sulphates               float64
alcohol                 float64
quality                   int64
Id                        int64
dtype: object

In [116]:
df.alcohol.dtype

dtype('float64')

In [117]:
#check datatypes of variable having space
df["fixed acidity"].dtype

dtype('float64')

In [118]:
#datatypes of only interger
df.select_dtypes(include='int').columns

Index(['quality', 'Id'], dtype='object')

In [119]:
#datatypes of types excluding interger
df.select_dtypes(exclude='int').columns

Index(['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
       'pH', 'sulphates', 'alcohol'],
      dtype='object')

In [120]:
df.iloc[0:2,0:4]

   fixed acidity  volatile acidity  citric acid  residual sugar
0            7.4              0.70          0.0             1.9
1            7.8              0.88          0.0             2.6

In [121]:
df['fixed acidity'][0]

np.float64(7.4)

In [122]:
df.iat[2,1]

np.float64(0.76)

In [123]:
#missing values
df.isnull().sum()

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
Id                      0
dtype: int64

In [124]:
df.notnull().sum()

fixed acidity           1143
volatile acidity        1143
citric acid             1143
residual sugar          1143
chlorides               1143
free sulfur dioxide     1143
total sulfur dioxide    1143
density                 1143
pH                      1143
sulphates               1143
alcohol                 1143
quality                 1143
Id                      1143
dtype: int64

In [125]:
#drops the nan values
df.dropna()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id
0,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5,0
1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5,1
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5,2
3,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6,3
4,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1138,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6,1592
1139,6.8,0.620,0.08,1.9,0.068,28.0,38.0,0.99651,3.42,0.82,9.5,6,1593
1140,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5,1594
1141,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,6,1595
1142,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5,1597

In [126]:
#filling nan values
df.fillna(0)

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id
0,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5,0
1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5,1
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5,2
3,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6,3
4,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1138,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6,1592
1139,6.8,0.620,0.08,1.9,0.068,28.0,38.0,0.99651,3.42,0.82,9.5,6,1593
1140,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5,1594
1141,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,6,1595
1142,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5,1597

In [127]:
#filling nan values with mean
df.fillna(df.mean)

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id
0,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5,0
1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5,1
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5,2
3,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6,3
4,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1138,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6,1592
1139,6.8,0.620,0.08,1.9,0.068,28.0,38.0,0.99651,3.42,0.82,9.5,6,1593
1140,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5,1594
1141,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,6,1595
1142,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5,1597

In [128]:
#check duplicates
df.duplicated().sum

<bound method Series.sum of 0       False
1       False
2       False
3       False
4       False
        ...
1138    False
1139    False
1140    False
1141    False
1142    False
Length: 1143, dtype: bool>

In [129]:
#drop duplicate without inplace the process is temporary
df.drop_duplicates(inplace=True)

In [130]:
#sortd by column alcohol
df.sort_values(by="alcohol")

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id
388,14.3,0.31,0.74,1.8,0.075,6.0,15.0,1.00080,2.86,0.79,8.4,6,544
368,10.4,0.61,0.49,2.1,0.200,5.0,16.0,0.99940,3.16,0.63,8.4,3,517
1023,10.0,0.38,0.38,1.6,0.169,27.0,90.0,0.99914,3.15,0.65,8.5,5,1436
263,7.9,0.24,0.40,1.6,0.056,11.0,25.0,0.99670,3.32,0.87,8.7,6,371
1051,9.9,0.50,0.50,13.8,0.205,48.0,82.0,1.00242,3.16,0.75,8.8,5,1474
...,...,...,...,...,...,...,...,...,...,...,...,...,...
589,4.9,0.42,0.00,2.1,0.048,16.0,42.0,0.99154,3.71,0.74,14.0,7,821
419,5.0,0.42,0.24,2.0,0.060,19.0,50.0,0.99170,3.72,0.74,14.0,8,588
98,5.2,0.34,0.00,1.8,0.050,27.0,63.0,0.99160,3.68,0.79,14.0,6,144
96,5.2,0.34,0.00,1.8,0.050,27.0,63.0,0.99160,3.68,0.79,14.0,6,142
462,15.9,0.36,0.65,7.5,0.096,22.0,71.0,0.99760,2.98,0.84,14.9,5,652

In [131]:
#sample 5 give 5 random rows and .sort arranges in ascending order
df.sample(5).sort_index()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id
30,7.5,0.49,0.20,2.6,0.332,8.0,14.0,0.99680,3.21,0.90,10.5,6,42
668,8.3,0.28,0.48,2.1,0.093,6.0,12.0,0.99408,3.26,0.62,12.4,7,947
696,7.7,0.39,0.12,1.7,0.097,19.0,27.0,0.99596,3.16,0.49,9.4,5,990
781,9.1,0.30,0.41,2.0,0.068,10.0,24.0,0.99523,3.27,0.85,11.7,7,1107
998,8.2,0.24,0.34,5.1,0.062,8.0,22.0,0.99740,3.22,0.94,10.9,6,1406

In [132]:
#again sample give 7 random rows, ignore index makes the index start from 0 instead of their actual index
df.sample(7,ignore_index=True).sort_index(ascending=True)

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id
0,12.6,0.410,0.54,2.8,0.103,19.0,41.0,0.99939,3.21,0.76,11.3,6,814
1,6.2,0.785,0.00,2.1,0.060,6.0,13.0,0.99664,3.59,0.61,10.0,4,1461
2,6.2,0.460,0.29,2.1,0.074,32.0,98.0,0.99578,3.33,0.62,9.8,5,1583
3,7.8,0.630,0.48,1.7,0.100,14.0,96.0,0.99610,3.19,0.62,9.5,5,165
4,11.8,0.380,0.55,2.1,0.071,5.0,19.0,0.99860,3.11,0.62,10.8,6,699
5,10.0,0.430,0.33,2.7,0.095,28.0,89.0,0.99840,3.22,0.68,10.0,5,1128
6,8.0,0.715,0.22,2.3,0.075,13.0,81.0,0.99688,3.24,0.54,9.5,6,1278

In [133]:
#check next
df.sample(5).reset_index()

,index,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id
0,352,10.7,0.35,0.53,2.6,0.070,5.0,16.0,0.99720,3.15,0.65,11.0,8,498
1,19,7.6,0.41,0.24,1.8,0.080,4.0,11.0,0.99620,3.28,0.59,9.5,5,26
2,682,9.0,0.40,0.43,2.4,0.068,29.0,46.0,0.99430,3.20,0.60,12.2,6,968
3,840,9.1,0.40,0.57,4.6,0.080,6.0,20.0,0.99652,3.28,0.57,12.5,6,1190
4,155,7.5,0.49,0.19,1.9,0.076,10.0,44.0,0.99570,3.39,0.54,9.7,5,218

In [134]:
#check index
df.sample(5).reset_index(drop=True)

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id
0,10.0,0.690,0.11,1.4,0.084,8.0,24.0,0.99578,2.88,0.47,9.7,5,1470
1,9.1,0.765,0.04,1.6,0.078,4.0,14.0,0.99800,3.29,0.54,9.7,4,704
2,8.0,0.450,0.23,2.2,0.094,16.0,29.0,0.99620,3.21,0.49,10.2,6,681
3,9.3,0.500,0.36,1.8,0.084,6.0,17.0,0.99704,3.27,0.77,10.8,6,1049
4,9.3,0.655,0.26,2.0,0.096,5.0,35.0,0.99738,3.25,0.42,9.6,5,761

In [135]:
#correlation
df.corr()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id
fixed acidity,1.000000,-0.250728,0.673157,0.171831,0.107889,-0.164831,-0.110628,0.681501,-0.685163,0.174592,-0.075055,0.121970,-0.275826
volatile acidity,-0.250728,1.000000,-0.544187,-0.005751,0.056336,-0.001962,0.077748,0.016512,0.221492,-0.276079,-0.203909,-0.407394,-0.007892
citric acid,0.673157,-0.544187,1.000000,0.175815,0.245312,-0.057589,0.036871,0.375243,-0.546339,0.331232,0.106250,0.240821,-0.139011
residual sugar,0.171831,-0.005751,0.175815,1.000000,0.070863,0.165339,0.190790,0.380147,-0.116959,0.017475,0.058421,0.022002,-0.046344
chlorides,0.107889,0.056336,0.245312,0.070863,1.000000,0.015280,0.048163,0.208901,-0.277759,0.374784,-0.229917,-0.124085,-0.088099
free sulfur dioxide,-0.164831,-0.001962,-0.057589,0.165339,0.015280,1.000000,0.661093,-0.054150,0.072804,0.034445,-0.047095,-0.063260,0.095268
total sulfur dioxide,-0.110628,0.077748,0.036871,0.190790,0.048163,0.661093,1.000000,0.050175,-0.059126,0.026894,-0.188165,-0.183339,-0.107389
density,0.681501,0.016512,0.375243,0.380147,0.208901,-0.054150,0.050175,1.000000,-0.352775,0.143139,-0.494727,-0.175208,-0.363926
pH,-0.685163,0.221492,-0.546339,-0.116959,-0.277759,0.072804,-0.059126,-0.352775,1.000000,-0.185499,0.225322,-0.052453,0.132904
sulphates,0.174592,-0.276079,0.331232,0.017475,0.374784,0.034445,0.026894,0.143139,-0.185499,1.000000,0.094421,0.257710,-0.103954
alcohol,-0.075055,-0.203909,0.106250,0.058421,-0.229917,-0.047095,-0.188165,-0.494727,0.225322,0.094421,1.000000,0.484866,0.238087
quality,0.121970,-0.407394,0.240821,0.022002,-0.124085,-0.063260,-0.183339,-0.175208,-0.052453,0.257710,0.484866,1.000000,0.069708
Id,-0.275826,-0.007892,-0.139011,-0.046344,-0.088099,0.095268,-0.107389,-0.363926,0.132904,-0.103954,0.238087,0.069708,1.000000

In [136]:
#unique
df["quality"].unique()

array([5, 6, 7, 4, 8, 3])

In [137]:
#no. of unique values
df["quality"].nunique()

6

In [138]:
df["fixed acidity"].unique()

array([ 7.4,  7.8, 11.2,  7.9,  7.3,  6.7,  5.6,  8.5,  7.6,  6.9,  6.3,
        7.1,  8.3,  5.2,  8.1,  8.8,  7.5,  4.6,  7.7,  6.6,  8.6, 10.2,
        7. ,  7.2,  8. ,  6.8,  6.2,  9.3,  5. ,  8.4, 10.1,  9.4,  8.2,
        5.8,  9.2,  8.9,  6.4, 11.5,  9.6, 12.8,  9.7,  8.7, 12. , 15. ,
       10.8, 11.1, 10. , 12.5, 10.3, 11.4,  9.9, 11.6, 10.4, 13.3, 10.6,
        9. ,  9.8, 13.4, 11.9, 10.9, 13.8,  9.1, 13.5,  6.1, 10.5, 12.6,
       13.7,  9.5, 12.2, 12.3, 15.6,  5.3, 11.3, 13. ,  6.5, 10.7, 12.9,
       14.3, 12.4, 15.5, 12.7, 13.2, 15.9,  5.1, 11.8,  4.9,  5.9, 11.7,
        5.4,  5.7,  6. ])

In [139]:
df["quality"].value_counts()

quality
5    483
6    462
7    143
4     33
8     16
3      6
Name: count, dtype: int64

In [140]:
#returns in true or false
df["quality"]>5

0       False
1       False
2       False
3        True
4       False
        ...
1138     True
1139     True
1140    False
1141     True
1142    False
Name: quality, Length: 1143, dtype: bool

In [141]:
#returns the actual values
df[df["quality"]>5]

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6,3
7,7.3,0.65,0.00,1.2,0.065,15.0,21.0,0.99460,3.39,0.47,10.0,7,7
8,7.8,0.58,0.02,2.0,0.073,9.0,18.0,0.99680,3.36,0.57,9.5,7,8
12,8.5,0.28,0.56,1.8,0.092,35.0,103.0,0.99690,3.30,0.75,10.5,7,16
13,7.9,0.32,0.51,1.8,0.341,17.0,56.0,0.99690,3.04,1.08,9.2,6,19
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1136,6.3,0.55,0.15,1.8,0.077,26.0,35.0,0.99314,3.32,0.82,11.6,6,1590
1137,5.4,0.74,0.09,1.7,0.089,16.0,26.0,0.99402,3.67,0.56,11.6,6,1591
1138,6.3,0.51,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6,1592
1139,6.8,0.62,0.08,1.9,0.068,28.0,38.0,0.99651,3.42,0.82,9.5,6,1593
1141,5.9,0.55,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,6,1595

In [142]:
#checking 2 statements at once
df[(df["quality"]>5) & (df["alcohol"]>10)]

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id
12,8.5,0.280,0.56,1.8,0.092,35.0,103.0,0.99690,3.30,0.75,10.5,7,16
26,7.8,0.600,0.14,2.4,0.086,3.0,15.0,0.99750,3.42,0.60,10.8,6,36
30,7.5,0.490,0.20,2.6,0.332,8.0,14.0,0.99680,3.21,0.90,10.5,6,42
38,7.6,0.510,0.15,2.8,0.110,33.0,73.0,0.99550,3.17,0.63,10.2,6,54
48,8.0,0.705,0.05,1.9,0.074,8.0,19.0,0.99620,3.34,0.95,10.5,6,69
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1135,5.8,0.610,0.11,1.8,0.066,18.0,28.0,0.99483,3.55,0.66,10.9,6,1587
1136,6.3,0.550,0.15,1.8,0.077,26.0,35.0,0.99314,3.32,0.82,11.6,6,1590
1137,5.4,0.740,0.09,1.7,0.089,16.0,26.0,0.99402,3.67,0.56,11.6,6,1591
1138,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6,1592
1141,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,6,1595

In [143]:
#increasing alcohol by 10 percent
df.alcohol*=1.10

In [144]:
def rating(quality):
    if quality>5:
        return "good"
    else:
        return "bad"

In [145]:
df['quality review']=df['quality'].apply(rating)
df.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id,quality review
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,10.34,5,0,bad
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,10.78,5,1,bad
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,10.78,5,2,bad
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,10.78,6,3,good
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,10.34,5,4,bad

In [146]:
#creates a new file without index
df.to_csv("Wine.csv",index=False,header=False)

In [147]:
df['quality_level']=df["quality"].map({3:'Very Bad', 4:'Bad',5:'Good',6:'Very Good',7:'Nice',8:'Excellent'})
df.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id,quality review,quality_level
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,10.34,5,0,bad,Good
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,10.78,5,1,bad,Good
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,10.78,5,2,bad,Good
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,10.78,6,3,good,Very Good
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,10.34,5,4,bad,Good

In [148]:
df["quality_level"].unique()

array(['Good', 'Very Good', 'Nice', 'Bad', 'Excellent', 'Very Bad'],
      dtype=object)

In [149]:
df["quality_level"].map({"Good":"Good1","Very Good":"VG2"})
df.head(10)

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id,quality review,quality_level
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,10.34,5,0,bad,Good
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,10.78,5,1,bad,Good
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,10.78,5,2,bad,Good
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,10.78,6,3,good,Very Good
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,10.34,5,4,bad,Good
5,7.4,0.66,0.00,1.8,0.075,13.0,40.0,0.9978,3.51,0.56,10.34,5,5,bad,Good
6,7.9,0.60,0.06,1.6,0.069,15.0,59.0,0.9964,3.30,0.46,10.34,5,6,bad,Good
7,7.3,0.65,0.00,1.2,0.065,15.0,21.0,0.9946,3.39,0.47,11.00,7,7,good,Nice
8,7.8,0.58,0.02,2.0,0.073,9.0,18.0,0.9968,3.36,0.57,10.45,7,8,good,Nice
9,6.7,0.58,0.08,1.8,0.097,15.0,65.0,0.9959,3.28,0.54,10.12,5,10,bad,Good

In [150]:
df.rename(columns={"fixed acidity":"Acidity"},inplace=False)
df.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id,quality review,quality_level
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,10.34,5,0,bad,Good
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,10.78,5,1,bad,Good
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,10.78,5,2,bad,Good
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,10.78,6,3,good,Very Good
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,10.34,5,4,bad,Good

In [151]:
df1=pd.read_csv("wine_data.csv")
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 220 entries, 0 to 219
Data columns (total 15 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   fixed acidity         220 non-null    float64
 1   volatile acidity      220 non-null    float64
 2   citric acid           220 non-null    float64
 3   residual sugar        220 non-null    float64
 4   chlorides             220 non-null    float64
 5   free sulfur dioxide   220 non-null    float64
 6   total sulfur dioxide  220 non-null    float64
 7   density               220 non-null    float64
 8   pH                    220 non-null    float64
 9   sulphates             220 non-null    float64
 10  alcohol               220 non-null    float64
 11  quality               220 non-null    int64
 12  Id                    220 non-null    int64
 13  name                  220 non-null    object
 14  date                  220 non-null    object
dtypes: float64(11), int64(2), object(2)
memory usage: 25.9+ KB

In [152]:
df1.name

0                                WineA
1                                WineB
2                                WineC
3                                WineD
4            Weingut Syrah Reserve 575
                    ...
215           Bodega Pinot Classic 513
216       Castello Merlot Grand Cru 41
217    Bodega Chardonnay Grand Cru 257
218       Chateau Cabernet Special 857
219       Bodega Sauvignon Classic 591
Name: name, Length: 220, dtype: object

In [153]:
df1.name.str.upper()

0                                WINEA
1                                WINEB
2                                WINEC
3                                WINED
4            WEINGUT SYRAH RESERVE 575
                    ...
215           BODEGA PINOT CLASSIC 513
216       CASTELLO MERLOT GRAND CRU 41
217    BODEGA CHARDONNAY GRAND CRU 257
218       CHATEAU CABERNET SPECIAL 857
219       BODEGA SAUVIGNON CLASSIC 591
Name: name, Length: 220, dtype: object

In [154]:
df1.name.str.capitalize()

0                                Winea
1                                Wineb
2                                Winec
3                                Wined
4            Weingut syrah reserve 575
                    ...
215           Bodega pinot classic 513
216       Castello merlot grand cru 41
217    Bodega chardonnay grand cru 257
218       Chateau cabernet special 857
219       Bodega sauvignon classic 591
Name: name, Length: 220, dtype: object

In [155]:
df1.name.str.title()

0                                Winea
1                                Wineb
2                                Winec
3                                Wined
4            Weingut Syrah Reserve 575
                    ...
215           Bodega Pinot Classic 513
216       Castello Merlot Grand Cru 41
217    Bodega Chardonnay Grand Cru 257
218       Chateau Cabernet Special 857
219       Bodega Sauvignon Classic 591
Name: name, Length: 220, dtype: object

In [156]:
pd.to_datetime(df1.date)

0     2023-01-10
1     2023-02-15
2     2023-03-20
3     2023-04-25
4     2023-02-12
         ...
215   2024-10-08
216   2024-06-03
217   2022-02-22
218   2022-02-12
219   2022-03-24
Name: date, Length: 220, dtype: datetime64[ns]

In [157]:
df1['date']=pd.to_datetime(df1['date'])

In [158]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1143 entries, 0 to 1142
Data columns (total 15 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   fixed acidity         1143 non-null   float64
 1   volatile acidity      1143 non-null   float64
 2   citric acid           1143 non-null   float64
 3   residual sugar        1143 non-null   float64
 4   chlorides             1143 non-null   float64
 5   free sulfur dioxide   1143 non-null   float64
 6   total sulfur dioxide  1143 non-null   float64
 7   density               1143 non-null   float64
 8   pH                    1143 non-null   float64
 9   sulphates             1143 non-null   float64
 10  alcohol               1143 non-null   float64
 11  quality               1143 non-null   int64
 12  Id                    1143 non-null   int64
 13  quality review        1143 non-null   object
 14  quality_level         1143 non-null   object
dtypes: float64(11), int64(2), object(2)
memory usage: 134.1+ KB

In [159]:
df1.date.dt.year

0      2023
1      2023
2      2023
3      2023
4      2023
       ...
215    2024
216    2024
217    2022
218    2022
219    2022
Name: date, Length: 220, dtype: int32

In [161]:
df1['Year']=df1['date'].dt.year

In [162]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 220 entries, 0 to 219
Data columns (total 16 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   fixed acidity         220 non-null    float64
 1   volatile acidity      220 non-null    float64
 2   citric acid           220 non-null    float64
 3   residual sugar        220 non-null    float64
 4   chlorides             220 non-null    float64
 5   free sulfur dioxide   220 non-null    float64
 6   total sulfur dioxide  220 non-null    float64
 7   density               220 non-null    float64
 8   pH                    220 non-null    float64
 9   sulphates             220 non-null    float64
 10  alcohol               220 non-null    float64
 11  quality               220 non-null    int64
 12  Id                    220 non-null    int64
 13  name                  220 non-null    object
 14  date                  220 non-null    datetime64[ns]
 15  Year                  220 non-null    int32
dtypes: datetime64[ns](1), float64(11), int32(1), int64(2), object(1)
memory usage: 26.8+ KB

In [165]:
df1.loc[5]

fixed acidity                                  8.72
volatile acidity                               0.56
citric acid                                    0.34
residual sugar                                  0.8
chlorides                                     0.059
free sulfur dioxide                            22.3
total sulfur dioxide                           59.8
density                                     0.99571
pH                                             3.35
sulphates                                      0.79
alcohol                                        9.79
quality                                           4
Id                                                6
name                    Bodega Riesling Special 559
date                            2024-05-09 00:00:00
Year                                           2024
Name: 5, dtype: object

In [168]:
df1.loc[len(df1)] = [9, .23, .55, .9, .047, 24, 61, .84569, 4.10, .47, 10.45, 5, 7,"Italiano Del Wine", "2024-02-05 00:00:00", 2024]

In [169]:
df1.head(-1)

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id,name,date,Year
0,8.50,0.28,0.56,1.8,0.092,35.0,103.0,0.99690,3.30,0.75,10.50,7,16,WineA,2023-01-10 00:00:00,2023
1,8.00,0.59,0.16,1.8,0.065,3.0,16.0,0.99620,3.42,0.92,10.50,7,128,WineB,2023-02-15 00:00:00,2023
2,9.60,0.32,0.47,1.4,0.056,9.0,24.0,0.99695,3.22,0.82,10.30,7,200,WineC,2023-03-20 00:00:00,2023
3,12.80,0.30,0.74,2.6,0.095,9.0,28.0,0.99940,3.20,0.77,10.80,7,205,WineD,2023-04-25 00:00:00,2023
4,9.91,0.45,0.49,2.8,0.053,21.9,60.5,0.99683,3.31,0.90,8.88,4,5,Weingut Syrah Reserve 575,2023-02-12 00:00:00,2023
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
215,10.62,0.38,0.41,3.0,0.072,24.8,55.7,0.99732,3.16,0.79,10.99,6,216,Bodega Pinot Classic 513,2024-10-08 00:00:00,2024
216,10.21,0.17,0.60,2.5,0.059,13.7,21.2,0.99388,3.21,0.72,11.25,7,217,Castello Merlot Grand Cru 41,2024-06-03 00:00:00,2024
217,11.29,0.36,0.46,2.8,0.082,26.6,40.2,0.99651,3.27,0.84,11.24,7,218,Bodega Chardonnay Grand Cru 257,2022-02-22 00:00:00,2022
218,9.21,0.36,0.51,2.6,0.082,10.3,19.6,0.99854,3.20,0.70,11.09,6,219,Chateau Cabernet Special 857,2022-02-12 00:00:00,2022
219,10.02,0.21,0.47,1.8,0.050,17.2,33.5,0.99676,3.04,0.70,11.37,7,220,Bodega Sauvignon Classic 591,2022-03-24 00:00:00,2022

In [180]:
#delete particular record
df.drop(index=11,inplace=True)

In [184]:
df3=df.drop(columns='pH')
df3

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,sulphates,alcohol,quality,Id,quality review,quality_level
0,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,0.56,10.34,5,0,bad,Good
1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,0.68,10.78,5,1,bad,Good
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,0.65,10.78,5,2,bad,Good
3,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,0.58,10.78,6,3,good,Very Good
5,7.4,0.660,0.00,1.8,0.075,13.0,40.0,0.99780,0.56,10.34,5,5,bad,Good
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1138,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,0.75,12.10,6,1592,good,Very Good
1139,6.8,0.620,0.08,1.9,0.068,28.0,38.0,0.99651,0.82,10.45,6,1593,good,Very Good
1140,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,0.58,11.55,5,1594,bad,Good
1141,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,0.76,12.32,6,1595,good,Very Good
1142,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,0.71,11.22,5,1597,bad,Good

In [186]:
df1["High_Alcohol"]=df.alcohol >=10
df1.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id,name,date,Year,High_Alcohol
0,8.50,0.28,0.56,1.8,0.092,35.0,103.0,0.99690,3.30,0.75,10.50,7,16,WineA,2023-01-10 00:00:00,2023,True
1,8.00,0.59,0.16,1.8,0.065,3.0,16.0,0.99620,3.42,0.92,10.50,7,128,WineB,2023-02-15 00:00:00,2023,True
2,9.60,0.32,0.47,1.4,0.056,9.0,24.0,0.99695,3.22,0.82,10.30,7,200,WineC,2023-03-20 00:00:00,2023,True
3,12.80,0.30,0.74,2.6,0.095,9.0,28.0,0.99940,3.20,0.77,10.80,7,205,WineD,2023-04-25 00:00:00,2023,True
4,9.91,0.45,0.49,2.8,0.053,21.9,60.5,0.99683,3.31,0.90,8.88,4,5,Weingut Syrah Reserve 575,2023-02-12 00:00:00,2023,NaN

In [187]:
df1["Wine_Type"]="Red Wine"
df1.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id,name,date,Year,High_Alcohol,Wine_Type
0,8.50,0.28,0.56,1.8,0.092,35.0,103.0,0.99690,3.30,0.75,10.50,7,16,WineA,2023-01-10 00:00:00,2023,True,Red Wine
1,8.00,0.59,0.16,1.8,0.065,3.0,16.0,0.99620,3.42,0.92,10.50,7,128,WineB,2023-02-15 00:00:00,2023,True,Red Wine
2,9.60,0.32,0.47,1.4,0.056,9.0,24.0,0.99695,3.22,0.82,10.30,7,200,WineC,2023-03-20 00:00:00,2023,True,Red Wine
3,12.80,0.30,0.74,2.6,0.095,9.0,28.0,0.99940,3.20,0.77,10.80,7,205,WineD,2023-04-25 00:00:00,2023,True,Red Wine
4,9.91,0.45,0.49,2.8,0.053,21.9,60.5,0.99683,3.31,0.90,8.88,4,5,Weingut Syrah Reserve 575,2023-02-12 00:00:00,2023,NaN,Red Wine

In [202]:
#merge and concat
data1={"Name":['A','B','C'],'Age':[22,25,32],"Salary":[10000,15000,30000]}

data2={"Name":['D','E','F','A'],'Age':[29,31,39,41],"Salary":[210000,115000,430000,450001]}

In [203]:
newdf1=pd.DataFrame(data1)
newdf2=pd.DataFrame(data2)

In [205]:
newdf1.head()

  Name  Age  Salary
0    A   22   10000
1    B   25   15000
2    C   32   30000

In [206]:
newdf2.head()

  Name  Age  Salary
0    D   29  210000
1    E   31  115000
2    F   39  430000
3    A   41  450001

In [207]:
pd.concat([newdf1,newdf2],ignore_index=True)

  Name  Age  Salary
0    A   22   10000
1    B   25   15000
2    C   32   30000
3    D   29  210000
4    E   31  115000
5    F   39  430000
6    A   41  450001

In [208]:
pd.concat([newdf1,newdf2],ignore_index=True,axis=1)

     0     1        2  3   4       5
0    A  22.0  10000.0  D  29  210000
1    B  25.0  15000.0  E  31  115000
2    C  32.0  30000.0  F  39  430000
3  NaN   NaN      NaN  A  41  450001

In [217]:
newdata=pd.concat([newdf1,newdf2],ignore_index=True,axis=False)
newdata.head(10)

  Name  Age  Salary
0    A   22   10000
1    B   25   15000
2    C   32   30000
3    D   29  210000
4    E   31  115000
5    F   39  430000
6    A   41  450001

In [218]:
newdata.head(10)

  Name  Age  Salary
0    A   22   10000
1    B   25   15000
2    C   32   30000
3    D   29  210000
4    E   31  115000
5    F   39  430000
6    A   41  450001

In [219]:
pd.merge(newdf1,newdf2, on='Age',how='outer')

  Name_x  Age  Salary_x Name_y  Salary_y
0      A   22   10000.0    NaN       NaN
1      B   25   15000.0    NaN       NaN
2    NaN   29       NaN      D  210000.0
3    NaN   31       NaN      E  115000.0
4      C   32   30000.0    NaN       NaN
5    NaN   39       NaN      F  430000.0
6    NaN   41       NaN      A  450001.0